import getVsCode from "./getVsCode";
import { IVscodeState } from "./typings";
export function getState(): Required<IVscodeState> {
  const vscode = getVsCode();
  const state = vscode.getState();

  return {
    addingSnippets: state?.addingSnippets || [],
    editingSnippetObjMap: state?.editingSnippetObjMap || {},
    snippetList: state?.snippetList || [],
    scrollY: state?.scrollY || 0,
  };
}

export const langIds = [
  "abap",
  "bat",
  "bibtex",
  "clojure",
  "coffeescript",
  "c",
  "cpp",
  "csharp",
  "dockercompose",
  "css",
  "cuda-cpp",
  "d",
  "pascal",
  "diff",
  "dockerfile",
  "erlang",
  "fsharp",
  "git-commit",
  "git-rebase",
  "go",
  "groovy",
  "handlebars",
  "haml",
  "haskell",
  "html",
  "ini",
  "java",
  "javascript",
  "javascriptreact",
  "json",
  "jsonc",
  "julia",
  "latex",
  "less",
  "lua",
  "makefile",
  "markdown",
  "objective-c",
  "objective-cpp",
  "ocaml",
  "pascal",
  "perl",
  "perl6",
  "php",
  "plaintext",
  "powershell",
  "jade",
  "pug",
  "python",
  "r",
  "razor",
  "ruby",
  "rust",
  "scss",
  "sass",
  "shaderlab",
  "shellscript",
  "slim",
  "sql",
  "stylus",
  "svelte",
  "swift",
  "typescript",
  "typescriptreact",
  "tex",
  "vb",
  "vue",
  "vue-html",
  "xml",
  "xsl",
  "yaml",
];
